media:
  input: public/assets
  output: /assets
  categories: [ "image", "document", "audio"]

content:
  - name: projects
    label: Udstillinger
    type: collection
    path: _projects
    view:
      fields: [ title, imageUrl, description, year ]
      primary: title
      sort: [ title, year ]
      default:
        sort: year
        order: desc
    fields:
      - name: slug
        label: Slug
        type: string
        description: "URL-friendly version of the title"
      - name: title
        label: Title
        type: string
        description: "Needs to be unique from title of any other project, otherwise pages will collide."
        required: true
      - name: year
        label: Year
        type: number
      - name: headerImageUrl
        label: Project Image
        type: image
        list: false
        description: "The project header image"
      - name: carouselImages
        label: Project Images
        type: object
        list: true
        fields:
          - name: url
            label: Image URL
            type: image
            required: true
          - name: caption
            label: Image Caption
            type: string
            description: "Optional caption for this image"
        description: "Project images for carousel - carousel is placed at the page bottom"
      - name: body
        label: Content
        type: rich-text
        description: "Use '/' to activate commands, mark text to edit it to links or style it. Also, importantly, for spacing between paragraphs use 2x 'shift+enter'."
        options:
          format: html

  - name: articles
    label: Artikler
    type: collection
    path: _articles
    view:
      fields: [ title, date, platform, externalUrl ]
      primary: title
      sort: [ date, title ]
      default:
        sort: date
        order: desc
    fields:
      - name: slug
        label: Slug
        type: string
        description: "URL-friendly version of the title"
      - name: title
        label: Title
        type: string
        description: "Needs to be unique from title of any other article, otherwise pages will collide."
        required: true
      - name: date
        label: Publication Date
        type: date
        required: true
      - name: platform
        label: Media Platform
        type: string
        description: "Name of the publication or media platform"
      - name: platformUrl
        label: Platform URL
        type: string
        pattern:
          regex: '^https?://.*$'
          message: "Please enter a valid URL starting with http:// or https://"
      - name: headerImageUrl
        label: Article Image
        type: image
        list: false
        description: "The article header image"
      - name: externalUrl
        label: External URL
        type: string
        description: "If provided, clicking on this article will navigate to this external URL instead of the article page. Please enter a valid URL starting with http:// or https://"
        required: false
      - name: body
        label: Content
        type: rich-text
        description: "Use '/' to activate commands, mark text to edit it to links or style it. Also, importantly, for spacing between paragraphs use 2x 'shift+enter'."
        options:
          format: html

  - name: cultprojects
    label: Kulturprojekter
    type: collection
    path: _cultprojects
    view:
      fields: [ title, year, externalUrl ]
      primary: title
      sort: [ year, title ]
      default:
        sort: year
        order: desc
    fields:
      - name: slug
        label: Slug
        type: string
        description: "URL-friendly version of the title"
      - name: title
        label: Title
        type: string
        description: "Needs to be unique from title of any other project, otherwise pages will collide."
        required: true
      - name: year
        label: Year
        type: number
      - name: headerImageUrl
        label: Project Image
        type: image
        list: false
        description: "The project header image"
      - name: externalUrl
        label: External URL
        type: string
        description: "If provided, clicking on this article will navigate to this external URL instead of the article page. Please enter a valid URL starting with http:// or https://"
        required: false
      - name: body
        label: Content
        type: rich-text
        description: "Use '/' to activate commands, mark text to edit it to links or style it. Also, importantly, for spacing between paragraphs use 2x 'shift+enter'."
        options:
          format: html
      - name: carouselImages
        label: Project Images
        type: object
        list: true
        fields:
          - name: url
            label: Image URL
            type: image
            required: true
          - name: caption
            label: Image Caption
            type: string
            description: "Optional caption for this image"
        description: "Project images for carousel - carousel is placed at the page bottom"


  - name: about
    label: About
    type: file
    path: about.md
    format: yaml-frontmatter
    fields:
      - name: sections
        label: CV Sections
        type: object
        list: true
        fields:
          - name: title
            label: Section Title
            type: string
            required: true
          - name: items
            label: Section Items
            type: text
            list: true
      - name: body
        label: Content
        type: rich-text
        description: "Use '/' to activate commands, mark text to edit it to links or style it. Also, importantly, for spacing between paragraphs use 2x 'shift+enter'."
        options:
          format: html

  - name: index
    label: Hjem
    type: file
    path: index.md
    format: yaml-frontmatter
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: imageUrl
        label: Hero Image
        type: image
        description: "Main image for the homepage"
      - name: message
        label: About
        type: rich-text
        description: "Use '/' to activate commands, mark text to edit it to links or style it. Also, importantly, for spacing between paragraphs use 2x 'shift+enter'."
        options:
          format: html
      - name: body
        label: Content
        type: rich-text
        description: "Use '/' to activate commands, mark text to edit it to links or style it. Also, importantly, for spacing between paragraphs use 2x 'shift+enter'."
        options:
          format: html

  - name: press
    label: Presse
    type: file
    path: press.md
    format: yaml-frontmatter
    fields:
      - name: items
        label: Press Items
        type: object
        list: true
        fields:
          - name: title
            label: Article Title
            type: string
            required: true
          - name: articleDate
            label: date
            type: date
            required: true
          - name: url
            label: Article URL
            type: string
            required: true
            pattern: 
              regex: '^https?://.*$'
              message: "Please enter a valid URL starting with http:// or https://"
      - name: body
        label: Content
        type: rich-text
        description: "Use '/' to activate commands, mark text to edit it to links or style it. Also, importantly, for spacing between paragraphs use 2x 'shift+enter'."
        options:
          format: html

  - name: contact
    label: Kontakt
    type: file
    path: contact.md
    format: yaml-frontmatter
    fields:
      - name: title
        label: Title
        type: string
        required: true
        default: "Kontakt"
      - name: email
        label: Email Address
        type: string
        pattern:
          regex: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
          message: "Please enter a valid email address"
      - name: body
        label: Content
        type: rich-text
        description: "Use '/' to activate commands, mark text to edit it to links or style it. Also, importantly, for spacing between paragraphs use 2x 'shift+enter'."
        options:
          format: html

  - name: social
    label: SoMe
    type: file
    path: _data/social.json
    format: json
    fields:
      - name: linkedin
        label: LinkedIn URL
        type: string
        pattern:
          regex: '^https?://.*$'
          message: "Please enter a valid URL starting with http:// or https://"
      - name: instagram
        label: Instagram URL
        type: string
        pattern:
          regex: '^https?://.*$'
          message: "Please enter a valid URL starting with http:// or https://"
      - name: showInHeader
        label: Show in Header
        type: boolean
        default: true
        description: "Display social media icons in the top right corner of the website"


  - name: blog
    label: Blog
    type: collection
    path: _blog
    view:
      fields: [ title, date]
      primary: title
      sort: [ date, title ]
      default:
        sort: date
        order: desc
    fields:
      - name: slug
        label: Slug
        type: string
        description: "URL-friendly version of the title"
      - name: title
        label: Title
        type: string
        description: "Needs to be unique from title of any other article, otherwise pages will collide."
        required: true
      - name: date
        label: Publication Date
        type: date
        required: true
      - name: headerImageUrl
        label: Article Image
        type: image
        list: false
        description: "The article header image"
      - name: body
        label: Content
        type: rich-text
        description: "Use '/' to activate commands, mark text to edit it to links or style it. Also, importantly, for spacing between paragraphs use 2x 'shift+enter'."
        options:
          format: html
